DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS Guest;
DROP TABLE IF EXISTS Apartment;
DROP TABLE IF EXISTS Building;



CREATE TABLE Building(
	BuildingID INT PRIMARY KEY AUTO_INCREMENT,
	Manager VARCHAR(20),
	Address VARCHAR(100),
	Name VARCHAR(50)
);


CREATE TABLE Apartment(
	ApartID INT PRIMARY KEY AUTO_INCREMENT,
	ApartNum INT,
	ApartType VARCHAR(20),
	BuildingID INT,
	CONSTRAINT BuildingID_FK FOREIGN KEY (BuildingID) REFERENCES Building(BuildingID)
);

CREATE TABLE Guest(
	GuestID INT PRIMARY KEY AUTO_INCREMENT,
	FirstName VARCHAR(20),
	LastName VARCHAR(20)
);


CREATE TABLE Booking(
	BookID INT PRIMARY KEY AUTO_INCREMENT,
	ApartID INT,
	GuestID INT,
	DateStart DATE,
	DateEnd DATE,
	CONSTRAINT ApartID_FK FOREIGN KEY (ApartID) REFERENCES Apartment(ApartID),
	CONSTRAINT GuestID_FK FOREIGN KEY (GuestID) REFERENCES Guest(GuestID)
);
